# -*- coding: utf-8 -*-
"""untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/facusalass/8b7c466af2f73f273199db888d0b07cb/untitled1.ipynb
"""

!pip install openai==0.28

import openai

# Configura tu clave de API aquí
openai.api_key ="sk-None-CjDFp8sgHnJEKFWLr5GUT3BlbkFJNzuoLM9N0i3JMeKb14e9"

def generar_prompt(prompt, max_tokens, temperature):
    response = openai.Completion.create(
        model="gpt-3.5-turbo",  # Update to the new model
        prompt=prompt,
        max_tokens=max_tokens,
        temperature=temperature
    )
    return response.choices[0].text

configuraciones = [
    {"max_tokens": 50, "temperature": 0.5},
    {"max_tokens": 100, "temperature": 0.7},
    {"max_tokens": 150, "temperature": 1.0},
]

# Probar cada configuración
prompt = "¿Qué recomendaciones de productos tienes para mí?"
resultados = []

for config in configuraciones:
    respuesta = generar_prompt(prompt, max_tokens=config["max_tokens"], temperature=config["temperature"])
    resultados.append((config, respuesta))

for config, respuesta in resultados:
    print(f"Config: {config}")
    print(f"Respuesta: {respuesta}\n")